server:
    shutdown: graceful
    servlet:
        context-path: /api

spring:
    lifecycle:
        timeout-per-shutdown-phase: "60s"

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${MYSQL_URL}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}

    jackson:
        property-naming-strategy: SNAKE_CASE

    jpa:
        generate-ddl: false
        show-sql: true
        open-in-view: false

        hibernate:
            format_sql: true

    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}

jwt:
    accessExp: ${JWT_ACCESS_EXP}
    refreshExp: ${JWT_REFRESH_EXP}
    secretKey: ${JWT_SECRET}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}

kakao:
    restapi:
        key: ${KAKAO_RESTAPI_KEY}