server:
    shutdown: graceful

spring:
    lifecycle:
        timeout-per-shutdown-phase: "60s"

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${MYSQL_URL}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}

    jackson:
        property-naming-strategy: SNAKE_CASE

    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: false
        show-sql: true
        open-in-view: false

        hibernate:
            ddl-auto: create-drop


    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        password: ${REDIS_PASSWORD}

auth:
    jwt:
        accessExp: ${JWT_EXP_ACCESS}
        refreshExp: ${JWT_EXP_REFRESH}
        secret: ${JWT_SECRET_KEY}